name = "Cobblemon Evolved"
author = "Soken"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "252a59327427a078825af50061151a2bdcdc1160b8e9986837ca1e270b5b3ff6"

[versions]
fabric = "0.16.9"
minecraft = "1.21.1"
