name = "Cobblemon Evolved"
author = "Soken"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "278e94d12d0d26b6a8ff67af07dfa75da19261a5496f28d0e6a4d8454a55fdad"

[versions]
fabric = "0.16.9"
minecraft = "1.21.1"

[options]
acceptable-game-versions = ["1.20.1"]
